uci set wireless."$WIFI_ID"='wifi-iface';
uci set wireless."$WIFI_ID".device=$WIFI_DEV;
uci set wireless."$WIFI_ID".mode=$WIFI_MODE;
uci set wireless."$WIFI_ID".network="$($WIFI_ID $WIFI_SSID)";
uci set wireless."$WIFI_ID".ssid=$WIFI_SSID;
uci set wireless."$WIFI_ID".encryption=$WIFI_ENCRYPT;
uci set wireless."$WIFI_ID".key=$WIFI_KEY;
uci set wireless."$WIFI_ID".channel=$WIFI_CHANNEL;
uci set wireless."$WIFI_ID".isolate=$WIFI_ISOLATE;
uci set wireless."$WIFI_ID".hidden=$WIFI_HIDE;
uci commit wireless;
wifi reload;
uci -q show wireless.$WIFI_NETWORK;