uci set wireless."$WIFI_SSID"='wifi-iface';
uci set wireless."$WIFI_SSID".device=$WIFI_DEV;
uci set wireless."$WIFI_SSID".mode=$WIFI_MODE;
uci set wireless."$WIFI_SSID".network=$WIFI_NETWORK;
uci set wireless."$WIFI_SSID".ssid=$WIFI_SSID;
uci set wireless."$WIFI_SSID".encryption=$WIFI_ENCRYPT;
uci set wireless."$WIFI_SSID".key=$WIFI_KEY;
uci set wireless."$WIFI_SSID".channel=$WIFI_CHANNEL;
uci set wireless."$WIFI_SSID".isolate=$WIFI_ISOLATE;
uci set wireless."$WIFI_SSID".hidden=$WIFI_HIDE;
uci commit wireless;
wifi reload;